### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by Art4** [GevaterTod4711/Minesweeper#8]
Mein Vorschlag:

- [ ] 1. #9 Slim Framework einsetzen und nur eine index.php verwenden
- [ ] 2. Datenbank-Connection über Eloquent: https://www.slimframework.com/docs/cookbook/database-eloquent.html
- [ ] 3. User-Model erstellen
- [ ] 4. Google-Login mit https://github.com/thephpleague/oauth2-google
- [ ] 5. Facebook-Login mit https://github.com/thephpleague/oauth2-facebook

**Comment by Art4** [comment]
Endpoints:

- `/`: Zeige Login oder Highscore
- `/login`: Login über Google/Facebook
- `/login-callback`: OAuth2-Callback
- `/game`: Minesweeper

**Comment by Art4** [comment]
- [x] Registrierung
- [x] Login
- [x] Spiel nur nach Login erreichbar
- [ ] Editierbares Profil
